apiVersion: v1
kind: Namespace
metadata:
  name: fortnitestats
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: fortnitestats
  namespace: fortnitestats
spec:
  hard:
    persistentvolumeclaims: 0
    pods: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fortnitestats-player
  namespace: fortnitestats
data:
  player.txt: |-
    Player1
    Player2
    Player3
---
apiVersion: v1
kind: Secret
metadata:
  name: fortnitestats-secrets
  namespace: fortnitestats
type: Opaque
data:
  FORTNITE_API_TOKEN: ###FORTNITE_API_TOKEN###
  INFLUXDB_BUCKET: ###INFLUXDB_BUCKET###
  INFLUXDB_ORG: ###INFLUXDB_ORG###
  INFLUXDB_TOKEN: ###INFLUXDB_TOKEN###
  INFLUXDB_URL: ###INFLUXDB_URL###
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: fortnitestats
  namespace: fortnitestats
spec:
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          securityContext:
            fsGroup: 1000
          containers:
            - name: fortnitestats
              image: ghcr.io/aessing/fortnitestats-2-influxdb:0.2.2
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 0.25
                  memory: 64Mi
                requests:
                  cpu: 0.15
                  memory: 32Mi
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  add:
                    - NET_RAW
                  drop:
                    - ALL
                readOnlyRootFilesystem: true
                runAsGroup: 1000
                runAsNonRoot: true
                runAsUser: 1000
                seccompProfile:
                  type: RuntimeDefault
              env:
                - name: FORTNITE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: FORTNITE_API_TOKEN
                      name: fortnitestats-secrets
                - name: INFLUXDB_URL
                  valueFrom:
                    secretKeyRef:
                      key: INFLUXDB_URL
                      name: fortnitestats-secrets
                  valueFrom:
                    secretKeyRef:
                      key: INFLUXDB_TOKEN
                      name: fortnitestats-secrets
                - name: INFLUXDB_ORG
                  valueFrom:
                    secretKeyRef:
                      key: INFLUXDB_ORG
                      name: fortnitestats-secrets
                - name: INFLUXDB_BUCKET
                  valueFrom:
                    secretKeyRef:
                      key: INFLUXDB_BUCKET
                      name: fortnitestats-secrets
              volumeMounts:
                - mountPath: /app/player.txt
                  name: player-volume
                  subPath: player.txt
          volumes:
            - configMap:
                name: fortnitestats-player
              name: player-volume
  schedule: '*/5 * * * *'
